# Generated by Django 2.1.2 on 2019-02-10 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0009_auto_20190210_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttable',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sport.Team', verbose_name='Команда'),
            preserve_default=False,
        ),
    ]
