# Generated by Django 2.1.2 on 2019-02-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0010_resulttable_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ['name'], 'verbose_name': 'вид спорта', 'verbose_name_plural': 'виды спорта'},
        ),
        migrations.RemoveField(
            model_name='compitition',
            name='date',
        ),
        migrations.AddField(
            model_name='team',
            name='name_team',
            field=models.CharField(db_index=True, default=1, max_length=100, verbose_name='Название команды'),
            preserve_default=False,
        ),
    ]
