# Generated by Django 2.1.2 on 2019-02-28 04:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0012_auto_20190222_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resulttable',
            name='compitition',
        ),
        migrations.RemoveField(
            model_name='resulttable',
            name='department',
        ),
        migrations.RemoveField(
            model_name='resulttable',
            name='team',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name_team',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='compitition',
            name='period',
        ),
        migrations.RemoveField(
            model_name='compitition',
            name='team_name',
        ),
        migrations.RemoveField(
            model_name='period',
            name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='teamresult',
            name='place',
        ),
        migrations.AddField(
            model_name='compitition',
            name='date',
            field=models.DateField(default=datetime.date(2019, 2, 28), verbose_name='Дата соревнования'),
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sport.Position', verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='not_resultable',
            field=models.BooleanField(default=False, verbose_name='Вне зачета'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='comments',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='teamresult',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Очки'),
        ),
        migrations.AddField(
            model_name='teamresult',
            name='result',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='compitition',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.Place', verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='type',
            field=models.CharField(choices=[('лич.', 'Личный'), ('ком.', 'Командный'), ('л.-к.', 'Лично-командный')], max_length=10, verbose_name='Тип спорта'),
        ),
        migrations.AlterField(
            model_name='teamresult',
            name='compitition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Compitition', verbose_name='Соревнование'),
        ),
        migrations.DeleteModel(
            name='ResultTable',
        ),
    ]
