# Generated by Django 2.1.2 on 2019-03-03 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0013_auto_20190228_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compitition',
            name='date',
            field=models.DateField(default=datetime.date(2019, 3, 3), verbose_name='Дата соревнования'),
        ),
    ]
