# Generated by Django 2.1.2 on 2019-03-05 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0014_auto_20190303_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='compitition',
            name='comment',
            field=models.CharField(default='', max_length=500, verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='compitition',
            name='date',
            field=models.DateField(default=datetime.date(2019, 3, 5), verbose_name='Дата соревнования'),
        ),
    ]
