# Generated by Django 2.1.2 on 2019-03-06 03:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0014_auto_20190302_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2019, 3, 6), verbose_name='Дата соревнования')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.Place', verbose_name='Место проведения')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Sport', verbose_name='Вид Спорта')),
            ],
        ),
        migrations.RemoveField(
            model_name='compitition',
            name='place',
        ),
        migrations.RemoveField(
            model_name='compitition',
            name='sport',
        ),
        migrations.AlterField(
            model_name='judge',
            name='compitition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Competition', verbose_name='Соревнование'),
        ),
        migrations.AlterField(
            model_name='sportsmanresult',
            name='compitition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Competition', verbose_name='Вид Спорта'),
        ),
        migrations.AlterField(
            model_name='team',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Competition', verbose_name='Вид Спорта'),
        ),
        migrations.AlterField(
            model_name='teamresult',
            name='compitition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Competition', verbose_name='Соревнование'),
        ),
        migrations.DeleteModel(
            name='Compitition',
        ),
    ]
