# Generated by Django 2.1.2 on 2019-03-08 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0015_auto_20190305_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compitition',
            name='comment',
        ),
        migrations.AlterField(
            model_name='compitition',
            name='date',
            field=models.DateField(default=datetime.date(2019, 3, 8), verbose_name='Дата соревнования'),
        ),
    ]
