# Generated by Django 2.1.2 on 2019-03-12 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0016_auto_20190308_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compitition',
            name='date',
            field=models.DateField(default=datetime.date(2019, 3, 12), verbose_name='Дата соревнования'),
        ),
    ]
