# Generated by Django 2.1.2 on 2019-03-14 10:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0017_auto_20190312_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compitition',
            name='date',
            field=models.DateField(default=datetime.date(2019, 3, 14), verbose_name='Дата соревнования'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sport.Position', verbose_name='Должность'),
        ),
    ]
