# Generated by Django 2.1.2 on 2019-03-16 04:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0018_auto_20190314_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionJudge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_position', models.CharField(choices=[('гл.судья', 'Главный судья'), ('судья', 'Cудья')], max_length=20, verbose_name='Класс судьи')),
            ],
        ),
        migrations.RemoveField(
            model_name='judge',
            name='compitition',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='judge_position',
        ),
        migrations.AlterField(
            model_name='compitition',
            name='date',
            field=models.DateField(default=datetime.date(2019, 3, 16), verbose_name='Дата соревнования'),
        ),
        migrations.AddField(
            model_name='competitionjudge',
            name='compitition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Compitition', verbose_name='Соревнование'),
        ),
        migrations.AddField(
            model_name='competitionjudge',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Judge', verbose_name='Судья'),
        ),
    ]
